FROM python:3.13-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    POETRY_VERSION=1.8.3 \
    POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_IN_PROJECT=false \
    POETRY_VIRTUALENVS_PATH="/opt/venv" \
    POETRY_NO_INTERACTION=1

# Instala ferramentas básicas, Poetry e libatomic (necessária para o node/pyright)
RUN apt-get update && apt-get install -y curl libatomic1 && \
    curl -sSL https://install.python-poetry.org | python3 - && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copia arquivos de dependência
COPY pyproject.toml poetry.lock* ./

# Instala todas as dependências incluindo dev
RUN poetry config virtualenvs.in-project false && \
    poetry install --with dev

# Copia código da aplicação
COPY . .

CMD ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
